ericchentch/erp-os-fe

components/modal/Modal.tsx, modules/language/inventory/DeleteDictionaryPopup.tsx, modules/language/management/LanguageManagement.tsx
=> modify ui language

components/form/date-picker/DatePicker.tsx, components/form/date-picker/inventory/DayModal.tsx, components/form/select/SelectCustom.tsx, lib/common-func/index.tsx, styles/globals.css
- [V] Bug fix (non-breaking change which fixes an issue)
- [V] My code follows the style guidelines of this project
- [ V] I have performed a self-review of my code
- [ V] I have commented my code, particularly in hard-to-understand areas
- [ V] I have made corresponding changes to the documentation
- [V ] My changes generate no new warnings
- [V ] I have added tests that prove my fix is effective or that my feature works
- [V ] New and existing unit tests pass locally with my changes
- [V ] Any dependent changes have been merged and published in downstream …
=> fixed position select

hooks/useApiCall.tsx
=> disable loading when fail

components/sidebar/SideIconItem.tsx, components/sidebar/Sidebar.tsx
=> modify-main-side-bar

components/layout/AuthLayout.tsx, components/layout/NextUiProviderTheme.tsx, components/navbar/NavBarInternal.tsx, components/sidebar/Sidebar.tsx, constants/apiRoutes.tsx, hooks/useApiCall.tsx, modules/login/LoginForm.tsx, modules/verify/VerifyForm.tsx, pages/404.tsx, pages/_app.tsx, pages/dashboard/index.tsx, pages/language/management.tsx, pages/paths/index.tsx, pages/permission/[id].tsx, pages/permission/create.tsx, pages/permission/management.tsx, pages/settings/index.tsx, pages/user/[id].tsx, pages/user/create.tsx, pages/user/index.tsx, pages/user/management.tsx, redux/share-store/slice.tsx, types/redux/ShareStore.tsx
=> Modify logic permission

components/403/index.tsx, components/index.tsx, components/layout/AuthLayout.tsx, hooks/useApiCall.tsx
=> modify logic path

components/sidebar/Sidebar.tsx, components/sidebar/SignOutButton.tsx
=> add signout button

components/layout/DefaultLayout.tsx, components/sidebar/Sidebar.tsx, components/sidebar/SignOutButton.tsx, hooks/index.tsx, hooks/useGetBreadCrumb.tsx, modules/language/management/LanguageManagement.tsx, modules/paths/management/PathsManagement.tsx, modules/permission/create/PermisstionCreate.tsx, modules/permission/detail/PermissionDetail.tsx, modules/permission/management/PermissionManagement.tsx, modules/user/create/UserCreate.tsx, modules/user/detail/UserDetail.tsx, modules/user/management/UserManagement.tsx
=> Modify UI sidebar

constants/apiRoutes.tsx, modules/paths/management/PathsManagement.tsx, modules/permission/management/PermissionManagement.tsx, modules/user/management/UserManagement.tsx
=> add table api

components/table/Table.tsx, hooks/useTranslation.tsx, modules/language/inventory/DictionaryCreatePopup.tsx, modules/language/inventory/IOCsvLanguage.tsx, modules/language/inventory/LanguageCreatePopup.tsx, modules/language/management/OneLanguage.tsx, modules/paths/create/CreatePathPopup.tsx, modules/paths/delete/DeletePathPopup.tsx, modules/paths/management/PathsManagement.tsx, modules/permission/create/PermisstionCreate.tsx, modules/permission/detail/PermissionDetail.tsx, modules/permission/inventory/DeletePermissionPopup.tsx, modules/permission/management/PermissionManagement.tsx, modules/user/detail/UserDetail.tsx
=> resize button

hooks/useGetBreadCrumb.tsx
=> fix bug breadcrumb

modules/permission/inventory/permission.inventory.tsx
=> change user follow response

modules/user/detail/UserDetail.tsx, modules/user/inventory/User.inventory.tsx, types/user/index.tsx
=> change userresponse

hooks/useGetBreadCrumb.tsx
=> fix breadcrumb id

components/modal/Modal.tsx, components/navbar/NavBarInternal.tsx, hooks/useGetBreadCrumb.tsx, modules/language/inventory/IOCsvLanguage.tsx, modules/user/inventory/UserForm.tsx
=> fix navbar zindex

components/dropdown/DropdownBase.tsx, components/form/date-picker/DatePicker.tsx, components/form/input/Input.tsx, modules/language/inventory/Language.inventory.tsx, modules/login/login.inventory.tsx, modules/paths/inventory/index.tsx, modules/permission/create/PermisstionCreate.tsx, modules/permission/inventory/ModifierPermission.tsx, modules/permission/inventory/permission.inventory.tsx, modules/sign-up/sign-up.inventory.tsx, modules/user/detail/UserDetail.tsx, modules/user/inventory/User.inventory.tsx, modules/verify/verify.inventory.tsx, styles/globals.css, types/permission/index.tsx
=> new-change-button-user

constants/apiRoutes.tsx, modules/paths/create/PathCreate.tsx, modules/paths/detail/PathDetail.tsx, modules/paths/inventory/Iventory.tsx, modules/paths/inventory/ModifierPath.tsx, modules/permission/detail/PermissionDetail.tsx, modules/user/detail/UserDetail.tsx, types/paths/index.tsx
=> add update path

components/layout/NextUiProviderTheme.tsx, modules/paths/detail/PathDetail.tsx, modules/permission/detail/PermissionDetail.tsx, modules/user/detail/UserDetail.tsx, package.json, pages/_app.tsx, yarn.lock
=> update detail and uppdate react toast

components/layout/GeneralProvider.tsx, components/navbar/NavBarInternal.tsx, constants/apiRoutes.tsx, modules/settings/inventory/general-setting/GeneralSettings.tsx, modules/user/inventory/User.inventory.tsx, pages/_app.tsx, redux/general-settings/slice.tsx, types/redux/GeneralSettings.tsx, types/user/index.tsx
=> add avt to setting

modules/permission/inventory/permission.inventory.tsx, modules/user/inventory/UserForm.tsx, types/user/index.tsx
=> Add avatar

styles/globals.css
=> add darkmode for scroolbar

components/403/index.tsx, components/layout/AuthLayout.tsx, modules/user/inventory/User.inventory.tsx, pages/403.tsx, pages/404.tsx, types/user/index.tsx
=> modify ui 403, 404

.eslintignore, components/layout/GeneralProvider.tsx, modules/per-authentication/login/LoginForm.tsx, modules/user/inventory/User.inventory.tsx, package.json, pages/_document.tsx, public/service-worker.js, types/user/index.tsx, yarn.lock
=> noti with pusher

Dockerfile
=> add docker build file

Dockerfile
=> modify build docker command

Dockerfile, app/entrypoint.sh
=> add docker entrypoint

Dockerfile, entrypoint.sh
=> add new entrypoint

components/layout/AuthLayout.tsx, components/layout/PusherProvider.tsx, redux/general-settings/slice.tsx
=> fix call access event

components/sidebar/Sidebar.tsx, pages/_app.tsx, redux/share-store/slice.tsx, types/navbar/index.tsx, types/redux/ShareStore.tsx
=> change sidebar to redux

pages/_app.tsx
=> change postion auth layout

components/sidebar/RenderItemSideBar.tsx, components/sidebar/SideIconItem.tsx, components/sidebar/SignOutButton.tsx, components/table/Table.tsx, hooks/useGetBreadCrumb.tsx, modules/permission/inventory/UserTable.tsx
=> Change hover sidebar

components/table/Table.tsx, hooks/useGetBreadCrumb.tsx
=> modify style table

components/navbar/NavBarInternal.tsx, components/sidebar/AccountInformation.tsx, components/sidebar/SettingButton.tsx, components/sidebar/Sidebar.tsx, components/sidebar/SignOutButton.tsx, modules/settings/inventory/UpdateAccount.tsx
=> 83 put user info in sidebar

components/sidebar/AccountInformation.tsx
=> add darkmode bg slidebar

components/button/FloatButton.tsx, components/float-tray/FloatTray.tsx, modules/user/inventory/FloatTrayCreate.tsx, modules/user/inventory/FloatTrayDetail.tsx, modules/user/management/UserManagement.tsx
=> change icon and upside icon

modules/language/inventory/DictionaryCreatePopup.tsx, modules/language/inventory/ExportLanguageFile.tsx, modules/language/inventory/FloatTrayLanguage.tsx, modules/language/inventory/InputLanguageFile.tsx, modules/language/inventory/LanguageCreatePopup.tsx, modules/language/management/LanguageManagement.tsx, modules/paths/create/PathCreate.tsx, modules/paths/detail/PathDetail.tsx, modules/paths/inventory/DeletePathPopup.tsx, modules/paths/inventory/FloatTrayCreate.tsx, modules/paths/inventory/FloatTrayDetail.tsx, modules/paths/inventory/FloatTrayManagement.tsx, modules/paths/management/PathsManagement.tsx, modules/permission/create/PermisstionCreate.tsx, modules/permission/detail/PermissionDetail.tsx, modules/permission/inventory/DeletePermissionPopup.tsx, modules/permission/inventory/FloatTrayCreate.tsx, modules/permission/inventory/FloatTrayDetail.tsx, modules/permission/management/PermissionManagement.tsx, modules/user/create/UserCreate.tsx, modules/user/detail/UserDetail.tsx, modules/user/management/UserManagement.tsx
=> add tray to permission, language, path

components/notification-sidebar/NotificationSidebar.tsx
=> reload noti weh noti come

components/notification-sidebar/NotificationSidebar.tsx
=> fix hook noti

components/notification-sidebar/NotificationSidebar.tsx, components/sidebar/Sidebar.tsx
=> sidebar can not click under 1280

package.json, yarn.lock
=> add local dev domain
